//! At-rest sealing for the local message store.
//!
//! # What this fixes
//!
//! `ios/ChatModule/ChatMessageStore.swift` stores `messages.payload` as the
//! **fully decrypted normalized row**: message text, `thumbnailBase64`,
//! `mediaKey`, and the original `encryptedContent` side by side. The file is
//! sandboxed and inherits iOS file protection, but nothing seals it at the
//! application layer. Non-claim 10.2.2 of the refactor doc says so plainly, and
//! this module is what makes that claim retractable for the new table.
//!
//! # AAD binds the row to its address, and that is the whole point
//!
//! `AAD = user_id ‖ 0x1F ‖ chat_id ‖ 0x1F ‖ message_id`.
//!
//! Without it, a sealed body is a portable blob: anyone who can write the
//! database — malware in a jailbroken container, a bad backup restore, a bug in
//! our own migration — could copy a row from one chat into another, or from one
//! user into another, and it would open cleanly and render as if it had always
//! been there. Binding the address makes relocation an authentication failure.
//! `a_row_cannot_be_relocated_to_another_message` is the test.
//!
//! **Note the asymmetry with the message envelope, which uses empty AAD.** That
//! is not an inconsistency to be tidied up: the wire envelope has deployed
//! readers on three platforms that would break if it started binding AAD. The
//! store seal is a brand-new format with no deployed readers, so it binds
//! properly from day one. Changing either to match the other would be a bug.
//!
//! # What lives where
//!
//! The 32-byte store key is generated by the platform with
//! `SecRandomCopyBytes` and held in the Keychain at
//! `kSecAttrAccessibleAfterFirstUnlockThisDeviceOnly` — the same class already
//! used for the RSA private key. **This crate never persists it** and never
//! writes it anywhere; it is handed in per session and lives only as long as the
//! sealer. No new cryptography is invented: this is the same AES-256-GCM
//! provider the message envelope already uses.

use std::sync::Arc;

use crate::crypto::VibeAeadProvider;
use crate::error::VibeCryptoError;
use crate::secret::{VibeNonce, VibePlaintext, VibeSecretKey, VIBE_TAG_LEN};

/// Largest row this module will seal or open, in bytes.
///
/// A normalized row is text plus metadata plus a thumbnail; media bytes ride the
/// media envelope and never appear here. The ceiling is checked before any
/// allocation so a corrupt or hostile row cannot make the app allocate without
/// bound during a restore.
pub const VIBE_STORE_MAX_ROW: usize = 4 << 20;

/// Field separator inside the AAD.
///
/// A byte that cannot appear in a user id, chat id, or message id, so
/// `("ab", "c", …)` and `("a", "bc", …)` cannot produce the same AAD. Without a
/// separator, concatenation is ambiguous and the binding is weaker than it looks.
const AAD_SEPARATOR: u8 = 0x1F;

/// The output of one seal: ciphertext and the nonce it used.
///
/// Deliberately NOT named `VibeSealedRow` — that name is frozen for
/// `vibe_core_store::VibeSealedRow`, which is a whole table row
/// (`message_id`, `ts_ms`, `flags`, plus these two fields). This type is just
/// the sealed payload; the store composes it into a row.
#[derive(Clone, PartialEq, Eq)]
pub struct VibeSealedBody {
    /// `ciphertext || tag`.
    pub sealed_body: Vec<u8>,
    pub seal_nonce: Vec<u8>,
}

impl std::fmt::Debug for VibeSealedBody {
    /// Lengths only. The body is ciphertext, but printing it in a crash report
    /// still hands an attacker a corpus, and this crate's rule is that errors
    /// and `Debug` carry shapes rather than data.
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("VibeSealedBody")
            .field("sealed_len", &self.sealed_body.len())
            .field("nonce_len", &self.seal_nonce.len())
            .finish()
    }
}

/// Why a seal or open failed.
///
/// `Crypto(AuthenticationFailed)` deliberately does not distinguish wrong key
/// from tampered ciphertext from relocated row: telling them apart is an oracle.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum VibeStoreSealError {
    /// Row beyond [`VIBE_STORE_MAX_ROW`].
    TooLarge,
    /// The stored nonce or body was structurally wrong — truncated, or a nonce
    /// of the wrong width. Distinct from an authentication failure because this
    /// one means "the database is damaged", not "someone tampered".
    Corrupt,
    Crypto(VibeCryptoError),
}

impl std::fmt::Display for VibeStoreSealError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::TooLarge => f.write_str("store row too large"),
            Self::Corrupt => f.write_str("store row corrupt"),
            Self::Crypto(e) => write!(f, "store seal crypto: {e}"),
        }
    }
}

impl std::error::Error for VibeStoreSealError {}

impl From<VibeCryptoError> for VibeStoreSealError {
    fn from(value: VibeCryptoError) -> Self {
        Self::Crypto(value)
    }
}

/// Seals and opens rows for the local store.
///
/// Holds the store key for the lifetime of the session and nothing else. No
/// `Debug` over the key, no serde, no accessor that hands it back out.
pub struct VibeStoreSealer {
    key: VibeSecretKey,
    aead: Arc<dyn VibeAeadProvider>,
}

impl std::fmt::Debug for VibeStoreSealer {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("VibeStoreSealer")
            .field("aead", &self.aead.label())
            .finish()
    }
}

impl VibeStoreSealer {
    /// Takes ownership of the store key for this session.
    ///
    /// The key arrives from the platform Keychain and is never written back to
    /// disk by this crate.
    pub fn new(key: VibeSecretKey, aead: Arc<dyn VibeAeadProvider>) -> Self {
        Self { key, aead }
    }

    /// Seals one normalized row.
    ///
    /// The nonce is generated here rather than accepted from the caller. A
    /// caller-supplied nonce is exactly how GCM nonce reuse happens, and nonce
    /// reuse under a single key is catastrophic — it leaks the XOR of two
    /// plaintexts and breaks the authentication guarantee outright. A backfill
    /// re-sealing 100,000 rows under one store key is precisely the workload
    /// where a careless caller would reuse one.
    pub fn seal(
        &self,
        user_id: &str,
        chat_id: &str,
        message_id: &str,
        plaintext: &[u8],
    ) -> Result<VibeSealedBody, VibeStoreSealError> {
        if plaintext.len() > VIBE_STORE_MAX_ROW {
            return Err(VibeStoreSealError::TooLarge);
        }
        let nonce = VibeNonce::random()?;
        let aad = row_aad(user_id, chat_id, message_id);
        let sealed_body = self.aead.seal(&self.key, &nonce, &aad, plaintext)?;
        Ok(VibeSealedBody {
            sealed_body,
            seal_nonce: nonce.as_bytes().to_vec(),
        })
    }

    /// Opens a row **at the address it claims to live at**.
    ///
    /// The caller passes the primary key it read the row under. If the row was
    /// moved, the AAD will not match and this fails closed.
    pub fn open(
        &self,
        user_id: &str,
        chat_id: &str,
        message_id: &str,
        sealed_body: &[u8],
        seal_nonce: &[u8],
    ) -> Result<VibePlaintext, VibeStoreSealError> {
        if sealed_body.len() > VIBE_STORE_MAX_ROW {
            return Err(VibeStoreSealError::TooLarge);
        }
        if sealed_body.len() < VIBE_TAG_LEN {
            return Err(VibeStoreSealError::Corrupt);
        }
        let nonce = VibeNonce::from_slice(seal_nonce).map_err(|_| VibeStoreSealError::Corrupt)?;
        let aad = row_aad(user_id, chat_id, message_id);
        self.aead
            .open(&self.key, &nonce, &aad, sealed_body)
            .map_err(VibeStoreSealError::from)
    }
}

/// `user_id ‖ 0x1F ‖ chat_id ‖ 0x1F ‖ message_id`.
fn row_aad(user_id: &str, chat_id: &str, message_id: &str) -> Vec<u8> {
    let mut aad = Vec::with_capacity(user_id.len() + chat_id.len() + message_id.len() + 2);
    aad.extend_from_slice(user_id.as_bytes());
    aad.push(AAD_SEPARATOR);
    aad.extend_from_slice(chat_id.as_bytes());
    aad.push(AAD_SEPARATOR);
    aad.extend_from_slice(message_id.as_bytes());
    aad
}

#[cfg(test)]
mod tests {
    use super::*;
    #[cfg(feature = "aead-aes-gcm")]
    use crate::crypto::default_aead_provider;
    use crate::crypto::VibeDenyAllAead;

    fn store_key() -> VibeSecretKey {
        VibeSecretKey::from_bytes([0x5A; 32])
    }

    #[cfg(feature = "aead-aes-gcm")]
    fn sealer() -> VibeStoreSealer {
        VibeStoreSealer::new(store_key(), default_aead_provider())
    }

    #[test]
    #[cfg(feature = "aead-aes-gcm")]
    fn a_row_round_trips_at_its_own_address() {
        let s = sealer();
        let row = s.seal("u1", "c1", "m1", b"normalized row json").unwrap();
        let opened = s
            .open("u1", "c1", "m1", &row.sealed_body, &row.seal_nonce)
            .unwrap();
        assert_eq!(opened.as_bytes(), b"normalized row json");
    }

    #[test]
    #[cfg(feature = "aead-aes-gcm")]
    fn a_row_cannot_be_relocated_to_another_message() {
        // The attack this prevents: copy a sealed row over another row's primary
        // key and have it render as that message.
        let s = sealer();
        let row = s.seal("u1", "c1", "m1", b"secret").unwrap();
        assert!(matches!(
            s.open("u1", "c1", "m2", &row.sealed_body, &row.seal_nonce),
            Err(VibeStoreSealError::Crypto(
                VibeCryptoError::AuthenticationFailed
            ))
        ));
    }

    #[test]
    #[cfg(feature = "aead-aes-gcm")]
    fn a_row_cannot_be_relocated_to_another_chat_or_user() {
        let s = sealer();
        let row = s.seal("u1", "c1", "m1", b"secret").unwrap();
        assert!(matches!(
            s.open("u1", "c2", "m1", &row.sealed_body, &row.seal_nonce),
            Err(VibeStoreSealError::Crypto(
                VibeCryptoError::AuthenticationFailed
            ))
        ));
        assert!(matches!(
            s.open("u2", "c1", "m1", &row.sealed_body, &row.seal_nonce),
            Err(VibeStoreSealError::Crypto(
                VibeCryptoError::AuthenticationFailed
            ))
        ));
    }

    #[test]
    #[cfg(feature = "aead-aes-gcm")]
    fn the_aad_separator_makes_concatenation_unambiguous() {
        // Without a separator, ("ab","c","m") and ("a","bc","m") would produce
        // the same AAD and a row would open at the wrong address.
        let s = sealer();
        let row = s.seal("ab", "c", "m", b"secret").unwrap();
        assert!(s
            .open("a", "bc", "m", &row.sealed_body, &row.seal_nonce)
            .is_err());
    }

    #[test]
    #[cfg(feature = "aead-aes-gcm")]
    fn tampering_with_the_body_fails_closed() {
        let s = sealer();
        let mut row = s.seal("u1", "c1", "m1", b"secret").unwrap();
        row.sealed_body[0] ^= 0xFF;
        assert!(matches!(
            s.open("u1", "c1", "m1", &row.sealed_body, &row.seal_nonce),
            Err(VibeStoreSealError::Crypto(
                VibeCryptoError::AuthenticationFailed
            ))
        ));
    }

    #[test]
    #[cfg(feature = "aead-aes-gcm")]
    fn a_wrong_store_key_opens_nothing() {
        let s = sealer();
        let row = s.seal("u1", "c1", "m1", b"secret").unwrap();
        let other = VibeStoreSealer::new(
            VibeSecretKey::from_bytes([0x11; 32]),
            default_aead_provider(),
        );
        assert!(other
            .open("u1", "c1", "m1", &row.sealed_body, &row.seal_nonce)
            .is_err());
    }

    #[test]
    #[cfg(feature = "aead-aes-gcm")]
    fn every_seal_uses_a_fresh_nonce() {
        // A backfill re-seals the whole history under one key. If the nonce were
        // caller-supplied or derived, this is where reuse would happen.
        let s = sealer();
        let a = s.seal("u1", "c1", "m1", b"same bytes").unwrap();
        let b = s.seal("u1", "c1", "m1", b"same bytes").unwrap();
        assert_ne!(a.seal_nonce, b.seal_nonce);
        assert_ne!(a.sealed_body, b.sealed_body);
    }

    #[test]
    #[cfg(feature = "aead-aes-gcm")]
    fn a_damaged_row_is_corrupt_not_an_authentication_failure() {
        // "The database is damaged" and "someone tampered" call for different
        // responses: the first is a re-backfill, the second is an incident.
        let s = sealer();
        let row = s.seal("u1", "c1", "m1", b"secret").unwrap();
        // `matches!` rather than `assert_eq!`: `VibePlaintext` has no `Debug` by
        // design, so a `Result` containing it cannot be compared or printed.
        assert!(matches!(
            s.open("u1", "c1", "m1", &row.sealed_body, &[0u8; 3]),
            Err(VibeStoreSealError::Corrupt)
        ));
        assert!(matches!(
            s.open("u1", "c1", "m1", &[0u8; 4], &row.seal_nonce),
            Err(VibeStoreSealError::Corrupt)
        ));
    }

    #[test]
    fn a_build_with_no_aead_provider_seals_nothing() {
        // Runs in both feature configurations. A store seal that silently
        // degraded would write plaintext into a column named `sealed_body`.
        let s = VibeStoreSealer::new(store_key(), Arc::new(VibeDenyAllAead));
        assert!(matches!(
            s.seal("u1", "c1", "m1", b"secret"),
            Err(VibeStoreSealError::Crypto(
                VibeCryptoError::ProviderUnavailable
            ))
        ));
        assert!(matches!(
            s.open("u1", "c1", "m1", &[0u8; 32], &[0u8; 12]),
            Err(VibeStoreSealError::Crypto(
                VibeCryptoError::ProviderUnavailable
            ))
        ));
    }

    #[test]
    fn an_oversized_row_is_refused_before_allocating() {
        let s = VibeStoreSealer::new(store_key(), Arc::new(VibeDenyAllAead));
        let huge = vec![0u8; VIBE_STORE_MAX_ROW + 1];
        assert_eq!(
            s.seal("u1", "c1", "m1", &huge),
            Err(VibeStoreSealError::TooLarge)
        );
        assert!(matches!(
            s.open("u1", "c1", "m1", &huge, &[0u8; 12]),
            Err(VibeStoreSealError::TooLarge)
        ));
    }

    #[test]
    fn neither_the_sealer_nor_a_sealed_row_prints_secrets() {
        let s = VibeStoreSealer::new(store_key(), Arc::new(VibeDenyAllAead));
        let rendered = format!("{s:?}");
        assert!(!rendered.contains("5a") && !rendered.contains("5A"));
        assert!(!rendered.contains("90")); // 0x5A as decimal

        let row = VibeSealedBody {
            sealed_body: vec![0xAB; 8],
            seal_nonce: vec![0xCD; 12],
        };
        let rendered = format!("{row:?}");
        assert!(rendered.contains("sealed_len"));
        assert!(!rendered.contains("ab") && !rendered.contains("AB"));
    }
}
